//
//  Workspace.swift
//  CustomTuistManifests
//
//  Created by Jaewon Yun on 2023/05/18.
//

import ProjectDescription

let workspace: Workspace = .init(
    name: "CustomTuist",
    projects: ["App", "Utility"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .relevant),
        lastXcodeUpgradeCheck: .init(14, 2, 0)
    )
)
