//
//  Workspace.swift
//  CustomTuistManifests
//
//  Created by Jaewon Yun on 2023/05/18.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace: Workspace = .init(
    name: "\(APPLICATION_NAME)",
    projects: ["\(APPLICATION_NAME)/**"],
    additionalFiles: [".gitignore"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled,
        lastXcodeUpgradeCheck: XCODE_VERSION
    )
)
