//
//  Workspace.swift
//  CustomTuistManifests
//
//  Created by Jaewon Yun on 2023/05/18.
//

import ProjectDescription

let workspace: Workspace = .init(
    name: "MyCounter",
    projects: ["MyCounter/App", "MyCounter/Utility", "MyCounter/Domain"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled,
        lastXcodeUpgradeCheck: .init(14, 2, 0)
    )
)
